config/routes.rb
Rails.application.routes.draw do
  root 'entries#index'
resources :entries

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
  	@entries = Entry.all
  end

  def show
  	@entry = Entry.find(params[:id])
  end

  def new
  	@entry = Entry.new
  end

  def create
  	if Entry.create(entry_params)
  		redirect_to entries_path
  	# @entry = Entry.new(entry_params)
  	else
  		render :new
  	end
  end

  private

  def entry_params
  	params.require(:entry).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<h1>Entries</h1>
<p><%= link_to 'New Post', new_entry_path %></p>
<% @entries.each do |entry| %>
	<h2><%= entry.title %></h2>
	<p><%= entry.body %></p>
	<%= link_to 'Show Entry', entry_path(entry) %>
<% end %>

app/views/entries/new.html.erb
<h1>Add a new entry</h1>

<%= form_for @entry do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :body %>
	<%= f.text_area :body%>
	<%= f.submit %>
<% end %>

app/views/entries/show.html.erb
<h1>Entry</h1>
<h2><%= @entry.title %></h2>
<p><%= @entry.body %></p>
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogPost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>